export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";

export const LOAD_ADVERTS_REQUEST = "LOAD_ADVERTS_REQUEST";
export const LOAD_ADVERTS_SUCCESS = "LOAD_ADVERTS_SUCCESS";
export const LOAD_ADVERTS_FAILURE = "LOAD_ADVERTS_FAILURE";

export const LOAD_ADVERT_REQUEST = "LOAD_ADVERT_REQUEST";
export const LOAD_ADVERT_SUCCESS = "LOAD_ADVERT_SUCCESS";
export const LOAD_ADVERT_FAILURE = "LOAD_ADVERT_FAILURE";

export const CREATE_ADVERT_REQUEST = "CREATE_ADVERT_REQUEST";
export const CREATE_ADVERT_SUCCESS = "CREATE_ADVERT_SUCCESS";
export const CREATE_ADVERT_FAILURE = "CREATE_ADVERT_FAILURE";

export const DELETE_ADVERT_REQUEST = "DELETE_ADVERT_REQUEST";
export const DELETE_ADVERT_SUCCESS = "DELETE_ADVERT_SUCCESS";
export const DELETE_ADVERT_FAILURE = "DELETE_ADVERT_FAILURE";

export const UI_RESET_ERROR = "UI_RESET_ERROR";

export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_TAGS_FAILURE = "LOAD_TAGS_FAILUIRE";

// export const AUTH_LOGIN = "AUTH_LOGIN";
// export const AUTH_LOGOUT = "AUTH_LOGOUT";
