export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const ADVERTS_LOADED = "ADVERTS_LOADED";
export const LOAD_ADVERTS_REQUEST = "LOAD_ADVERTS_REQUEST";
export const LOAD_ADVERTS_SUCCESS = "LOAD_ADVERTS_SUCCESS";
export const LOAD_ADVERTS_FAILURE = "LOAD_ADVERTS_FAILURE";

export const LOAD_ADVERT_REQUEST = "LOAD_ADVERT_REQUEST";
export const LOAD_ADVERT_SUCCESS = "LOAD_ADVERT_SUCCESS";
export const LOAD_ADVERT_FAILURE = "LOAD_ADVERT_FAILURE";

export const UI_RESET_ERROR = "UI_RESET_ERROR";


export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
